

POST http://localhost:3001/register
Content-Type: application/x-www-form-urlencoded
Referer: http://localhost:3000/

email=test1@gmail.com&password=testPassword&action=registration&fname=Darnell&lname=Chen&telephone=4047897733


###

POST http://localhost:3001/login
Content-Type: application/x-www-form-urlencoded
Referer: http://localhost:3000/

email=test@gmail.com&password=testPassword&action=login


###

POST http://localhost:3001/addMember
Content-Type: application/json
Referer: http://localhost:3000/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzE5MDI4ODQzLCJleHAiOjE3MTkwMzA2NDN9.SGLHxaVtPgAGwK5dnjBpnmzp911LeHErhelsb6mGfeg

{
    "name" : "John Doe",
    "number" : "XXX-XXX-XXXX"
}
###

GET http://localhost:3001/getData
Content-Type: application/json
Referer: http://localhost:3000/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzE5MDIyOTU0LCJleHAiOjE3MTkwMjQ3NTR9.3ygU-q6B9KR6gcrq4zed2sf2CnAHz3i9DHfC0HjOCN4

{}